**Modin pandas

The modin. pandas DataFrame is an extremely light-weight parallel DataFrame. Modin transparently distributes the data and computation so that all you need to do is continue using the pandas API as you were before installing Modin.

In [1]:
!pip install modin[ray]

Requirement already satisfied: modin[ray] in c:\users\rahul\anaconda3\lib\site-packages (0.15.2)
Requirement already satisfied: fsspec in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (2022.2.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (1.22.4)
Requirement already satisfied: packaging in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (21.3)
Requirement already satisfied: pandas==1.4.3 in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (1.4.3)
Requirement already satisfied: psutil in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (5.8.0)
Requirement already satisfied: pyarrow>=4.0.1 in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (8.0.0)
Collecting protobuf<4.0.0
  Downloading protobuf-3.20.3-cp39-cp39-win_amd64.whl (904 kB)
Requirement already satisfied: redis<4.0.0,>=3.5.0 in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (3.5.3)
Requirement already satisfied: ray[default]<1.13.0,>=1.4.0 in c:\users\rahul\anaconda3\lib\site-packages (from modin[ray]) (1.12.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\rahul\anaconda3\lib\site-packages (from pandas==1.4.3->modin[ray]) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rahul\anaconda3\lib\site-packages (from pandas==1.4.3->modin[ray]) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\rahul\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.4.3->modin[ray]) (1.16.0)
Requirement already satisfied: aiosignal in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Collecting grpcio<=1.43.0,>=1.28.1
  Downloading grpcio-1.43.0-cp39-cp39-win_amd64.whl (3.4 MB)
Requirement already satisfied: click>=7.0 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (8.0.4)
Requirement already satisfied: requests in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.27.1)
Requirement already satisfied: frozenlist in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Requirement already satisfied: pyyaml in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (6.0)
Requirement already satisfied: virtualenv in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (20.15.1)
Requirement already satisfied: attrs in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (21.4.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.0.2)
Requirement already satisfied: filelock in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.6.0)
Requirement already satisfied: jsonschema in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.4.0)
Requirement already satisfied: aiohttp-cors in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.7.0)
Requirement already satisfied: prometheus-client<0.14.0,>=0.7.1 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.13.1)
Requirement already satisfied: gpustat>=1.0.0b1 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.0.0rc1)
Requirement already satisfied: colorful in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.5.4)
Requirement already satisfied: smart-open in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (5.1.0)
Requirement already satisfied: opencensus in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.10.0)
Requirement already satisfied: aiohttp>=3.7 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.8.1)
Requirement already satisfied: py-spy>=0.2.0 in c:\users\rahul\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.3.12)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\rahul\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\rahul\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\rahul\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.6.3)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.12.3 requires grpcio>=1.48.2, but you have grpcio 1.43.0 which is incompatible.
google-auth-oauthlib 1.0.0 requires google-auth>=2.15.0, but you have google-auth 1.35.0 which is incompatible.

Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\rahul\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.0.4)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\rahul\anaconda3\lib\site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.1.1)
Requirement already satisfied: colorama in c:\users\rahul\anaconda3\lib\site-packages (from click>=7.0->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.4.4)
Requirement already satisfied: blessed>=1.17.1 in c:\users\rahul\anaconda3\lib\site-packages (from gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.19.1)
Requirement already satisfied: nvidia-ml-py<=11.495.46,>=11.450.129 in c:\users\rahul\anaconda3\lib\site-packages (from gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (11.495.46)
Requirement already satisfied: jinxed>=1.1.0 in c:\users\rahul\anaconda3\lib\site-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\rahul\anaconda3\lib\site-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.2.5)
Requirement already satisfied: ansicon in c:\users\rahul\anaconda3\lib\site-packages (from jinxed>=1.1.0->blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.89.0)
Requirement already satisfied: idna>=2.0 in c:\users\rahul\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\rahul\anaconda3\lib\site-packages (from jsonschema->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.18.0)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in c:\users\rahul\anaconda3\lib\site-packages (from opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.25.1)
Requirement already satisfied: opencensus-context>=0.1.2 in c:\users\rahul\anaconda3\lib\site-packages (from opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.1.2)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in c:\users\rahul\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.53.0)
Collecting google-auth<2.0dev,>=1.21.1
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Requirement already satisfied: setuptools>=40.3.0 in c:\users\rahul\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (61.2.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\rahul\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\rahul\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\rahul\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.2.8)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\rahul\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rahul\anaconda3\lib\site-packages (from requests->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\rahul\anaconda3\lib\site-packages (from requests->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.26.9)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\rahul\anaconda3\lib\site-packages (from packaging->modin[ray]) (3.0.4)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\rahul\anaconda3\lib\site-packages (from virtualenv->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.3.5)
Requirement already satisfied: platformdirs<3,>=2 in c:\users\rahul\anaconda3\lib\site-packages (from virtualenv->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.5.2)
Installing collected packages: protobuf, google-auth, grpcio
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.3
    Uninstalling protobuf-4.23.3:
      Successfully uninstalled protobuf-4.23.3
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.21.0
    Uninstalling google-auth-2.21.0:
      Successfully uninstalled google-auth-2.21.0
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.56.0
    Uninstalling grpcio-1.56.0:
      Successfully uninstalled grpcio-1.56.0
Successfully installed google-auth-1.35.0 grpcio-1.43.0 protobuf-3.20.3

In [2]:
import pandas as pd

In [3]:
%%time
df = pd.read_csv("titanic_train.csv")
df

CPU times: total: 0 ns
Wall time: 5.53 ms

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
%%time
df.groupby("Sex").count()

KeyError: 'sub_category'

In [8]:
import modin.pandas as mp

In [9]:
%%time
df_mp = mp.read_csv("titanic_train.csv")
df_mp

CPU times: total: 15.6 ms
Wall time: 38.5 ms

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
%%time
df_mp.groupby("sub_category").count()

KeyError: 'sub_category'